### ISSUE TITLE
Change ring splits to split on arbitrary letter ranges 

### ISSUE THREAD

**Issue by JohnFunk-VMW** [JohnFunkCode/zTournamentSorter#41]
New idea - add the start and end letters for the last name to the write_____Report methods.   This would make it easy to do multi-ring splits using arbitrary letter ranges.

**Comment by JohnFunkCode** [comment]
Changed the code to allow arbitrary splits in commit: https://github.com/JohnFunkCode/zTournamentSorter/commit/89c9e51b1aa224271ab5a13f0e69fce7fe19cf06

**Comment by JohnFunkCode** [comment]
Changed the code to allow arbitrary splits in commit: https://github.com/JohnFunkCode/zTournamentSorter/commit/89c9e51b1aa224271ab5a13f0e69fce7fe19cf06
